dynoleague/urls.py
from django.contrib import admin
from django.urls import path
from league import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('draftpicks', views.draft_pick_list, name='picks-list'),
    path('rosters', views.league_rosters, name='rosters'),
    path('', views.home, name='home'),
    path('leaguerules', views.league_rules, name='rules'),
    path('historyview', views.history, name='history'),
    path('updateplayers', views.update_players_view, name='updater'),
    path('team/<pk>', views.teams, name='team'),
]

league/models.py
from django.db import models
from django.db.models import Avg, Max, Min, StdDev, Sum


class Owner(models.Model):
    owner_name = models.CharField(max_length=100, unique=True, primary_key=True)
    owner_id = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.owner_name

    def avg_wins(self):
        obj = self.history.aggregate(Avg('wins'))
        return obj.get('wins__avg')

    def avg_place(self):
        obj = self.history.aggregate(Avg('place'))
        return obj.get('place__avg')

    def avg_points(self):
        obj = self.history.aggregate(Avg('points_for'))
        return obj.get('points_for__avg')


class FantasyTeam(models.Model):
    owner = models.ForeignKey(Owner, models.CASCADE, related_name='team')
    abbrev = models.CharField(max_length=15)
    name = models.CharField(max_length=50)
    year = models.IntegerField()
    division = models.IntegerField()


class PastSeason(models.Model):
    year = models.IntegerField()
    place = models.IntegerField()
    team_name = models.CharField(max_length=100, unique=False)
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE, related_name='history')
    wins = models.IntegerField()
    losses = models.IntegerField()
    ties = models.IntegerField()
    points_for = models.FloatField()
    points_against = models.FloatField()
    league_average = models.FloatField(blank=True, null=True)

    class Meta:
        ordering = ['year', 'place']

    def __str__(self):
        return str(self.year)

    
class CurrentSeason(models.Model):
    year = models.IntegerField(blank=True, null=True)
    game_week = models.IntegerField()
    team_name = models.CharField(max_length=100, unique=False)
    team_abbrev = models.CharField(max_length=100, unique=False)
    points_for = models.FloatField() # changed from 'poinst', this may cause DB issues
    opponent = models.CharField(max_length=100, unique=False)
    points_against = models.FloatField()
    result = models.IntegerField(default=0)
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE)
    point_dif = models.FloatField(blank=True, null=True)


    @property
    def margin(self):
        dif = self.points_for - self.points_against
        return dif

    def __str__(self):
        return 'GW ' + str(self.game_week)

    class Meta:
        ordering = ['-year', 'game_week']

# Needed models to eliminate constant espn API calls:
# Goes with function api_functions.get_standings


class Rankings(models.Model):
    year = models.IntegerField()
    game_week = models.IntegerField()
    team_name = models.CharField(max_length=100, unique=False)
    team_abbrev = models.CharField(max_length=100, unique=False)
    points_for = models.FloatField()
    points_against = models.FloatField()
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE)
    place = models.IntegerField()
    wins = models.IntegerField(blank=True, null=True)
    losses = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f"{self.place} place gw {self.game_week}"

    class Meta:
        ordering = ['game_week', 'place']


class NFLPlayer(models.Model):
    name = models.CharField(max_length=120, blank=True, null=True)
    team = models.CharField(max_length=120, blank=True, null=True)
    position = models.CharField(max_length=120, blank=True, null=True)
    roster = models.ForeignKey('Assets', models.CASCADE, related_name='players', blank=True, null=True)
    taxi = models.BooleanField(default=False)
    rostered = models.BooleanField(default=False)
    tenure = models.IntegerField(blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    height = models.CharField(max_length=8, blank=True, null=True)
    weight = models.CharField(max_length=8, blank=True, null=True)
    espn_id = models.CharField(max_length=125, blank=True, null=True)
    sleeper_id = models.CharField(max_length=125, blank=True, null=True)
    draft_capital = models.OneToOneField('DraftPick', models.CASCADE, related_name='draft_pick', blank=True, null=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['position', '-tenure']


class DraftPick(models.Model):
    year = models.IntegerField()
    round = models.IntegerField()
    pick = models.IntegerField(blank=True, null=True)  # won't know until after lottery
    owner =  models.ForeignKey('Assets', models.CASCADE, related_name='picks', blank=True, null=True)
 # Fix then, want entire chain of pick history

    class Meta:
        ordering = ['year', 'round', 'pick']

    def __str__(self):
        if self.pick:
            return f"{self.year} Rd {self.round}.{self.pick}"
        else:
            return f"{self.year} Rd {self.round}"
    
    # def history(self):
    #     return self.picktrade_set().all()  # is .all() needed?


class PickTrade(models.Model):
    pick = models.ForeignKey(DraftPick, models.CASCADE)
    traded_from = models.ForeignKey(Owner, models.CASCADE, related_name='pick_from')
    traded_to = models.ForeignKey(Owner, models.CASCADE, related_name='pick_to')
    date = models.DateField()  # default = 'now'


class Assets(models.Model):
    manager = models.OneToOneField(Owner, models.CASCADE)

    def __str__(self):
        return self.manager.owner_name


class LeagueRules(models.Model):
    number = models.IntegerField()
    title = models.CharField(max_length=127)
    rule = models.TextField()

    def __str__(self):
        return self.title

    def rule_split(self):
        points = self.rule.split('--')
        if points[0] == '':
            return points[1:]
        else:
            return points

    class Meta:
        ordering = ['number',]


class RuleProposal(models.Model):
    number = models.IntegerField(null=True, blank=True)
    name = models.CharField(max_length=127)
    proposal = models.TextField()
    result = models.CharField(max_length=56, blank=True, null=True)


    class Meta:
        ordering = ['number',]

    def __str__(self):
        return self.name


class Dates(models.Model):
    name = models.CharField(max_length=65)
    date = models.DateTimeField()

    def __str__(self):
        return self.name
    

league/views.py
from django.shortcuts import render
from league.models import DraftPick, Owner, LeagueRules, Dates, RuleProposal
from django.views.generic.list import ListView
from league.utils import PlayerUpdater
# Create your views here.
'''
needs:
view displaying tables of:
-- owner roster
-- owner taxi taxi_squad
-- owner picks

-- draft order with owner next to order
-- rules page

questions:
best way/package to provide tables (preferably sortable)

'''


def draft_pick_list(request):
    picks = DraftPick.objects.filter(year=2020)
    picks21 = DraftPick.objects.filter(year=2021)
    picks22 = DraftPick.objects.filter(year=2022)
    context = {
        'round1': picks.filter(round=1),
        'round2': picks.filter(round=2),
        'round3': picks.filter(round=3),
        'round4': picks.filter(round=4),
        'round5': picks.filter(round=5),
        'p21': picks21,
        'p22': picks22,
        }
    return render(request, 'league/draftpick_list.html', context)


def league_rosters(request):
    owners_list = Owner.objects.all()
    context = {'owners':owners_list}

    return render(request, 'league/rosters.html', context)


def home(request):
    dates = Dates.objects.all()
    new_rules = RuleProposal.objects.all()
    owners = Owner.objects.all()
    context = {
        'dates': dates,
        'props': new_rules,
        'owners': owners,
    }
    return render(request, 'league/home.html', context)


def history(request):
    owners = Owner.objects.all()
    context = {
        'owners':owners
    }
    return render(request, 'league/history.html', context)


def league_rules(request):
    rule_list = LeagueRules.objects.all()
    context = {'rules':rule_list}
    return render(request, 'league/rules.html', context)


def update_players_view(request):
    # if request.GET.get('mybtn'):
    upd = PlayerUpdater()
    upd.update()
    return render(request, 'league/update.html')


def teams(request, pk):
    team = Owner.objects.get(pk=pk)
    context = {'owner': team}
    return render(request, 'league/team.html', context)

templates/league/base.html
<!-- -------------------------- -->
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>RSWK Dyno League</title>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/61b0c0305c.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.css" rel="stylesheet">
   <style media="screen">
      {% comment %}
      resource: https://www.fantasyfootballdatapros.com/
      sortable tables: https://datatables.net/
      {% endcomment %}
      .boxy{
        background: #FFFFFF;
        border: 2px solid #FCA311;
        padding: 1.5% 1% 1% 1%;
        margin: 4%;
        border-radius: 10px;
        font-family: 'IBM Plex Sans', sans-serif;
        color: #14213D;

      }
      .date-box {
        background-color: #14213D;
        color: #FFFFFF;
        border: 2px solid #FCA311;
        border-radius: 3%;
        text-align: center;
        padding: 4% 2%;
        margin: 2%;
        height: 100%;
      }
      .fas{
        margin-right: 1rem;
      }
      .jumbotron {
        background-color: #414D64;
        color: #EEF4ED;
        border-radius: 0px;
      }
      .newrow{
        margin-right: 1%;
        justify-content: center;
        margin-bottom: 2%;
      }
      .last-row {
        border-bottom: 1px solid #14213D;
      }
      .roster-table{
        border-radius: 3px;
      }
      .nav-custom{
        background-color: #14213D;
      
      }
      th{
        text-align: center;
      }
      td{
        text-align: center;
      }
      .thead-custom {
        background-color: #14213D;
        color: #E5E5E5;
        font-family: 'IBM Plex Sans', sans-serif;

        font-weight:600;
      }
      .thead-gone {
        height: 1px;
        line-height: 1px;
        visibility: hidden;
      }
      .draft-table{
        margin-top:0em;
        margin-bottom:0em;
      }
      body{
        background-color: #E5E5E5;
        font-family: 'IBM Plex Sans', sans-serif;

      }
      #lineChart{
        background-color: #ffffff;
        border: 1px solid #171617;
        padding: 1.5%;
        border-radius: 3px;
      }
      #barChart{
        background-color: #ffffff;
        border: 1px solid #171617;
        padding: 1.5%;
        border-radius: 3px;
      }
      #barChart2{
        background-color: #ffffff;
        border: 1px solid #171617;
        padding: 1.5%;
        border-radius: 3px;
      }
      .chart-container{
        border: 2px solid #171617;
        color: #EEF4ED;
        padding: 1.5%;
        margin: 4px;
        border-radius: 3px;
      }
      .btn-custom {
        color: #FCA311;
        background-color: #14213D;
        border: 2px solid #FCA311;
        border-radius: 0em;
        font-weight: 500;
        font-size: medium; 
      }
      .sidebar-comp {
        color: #E5E5E5;
        background-color: #14213D;
      }
      .list-group-item.disabled {
        background-color: #14213D;
        color: #898989;
      }
      .rowone{
        padding-bottom: 20px;
      }
      .third{
        padding-top: 20px;
      }
      .weekly{
        margin-top: 30px;
        padding-top: 1rem;
      }
      .rule1 {
        background-color:#E5E5E5;
      }
      .rule2 {
        background-color: #FFFFFF;
      }
      .rule-list{
        padding: 3% 10% 2% 6%;
        color:#14213D;
      }
      #rule-jumbo{
        font-family: 'Cinzel', 'serif';
        font-size: large;
        text-align: center;
        margin-bottom: 0em;
        padding-bottom: 2em;
      }
      #email-btn {
        color:#14213D;
        background-color: #FCA311;
        border: 2px solid #14213D;
        font-weight: 500;
        font-size: medium;
        font-family: 'IBM Plex Sans', sans-serif; 
      }
      .teamtable {
        display: inline-block;
        min-width: min-content;
        max-width: initial;
      }
      body {
        overflow-x: hidden;
      }
      .roster-info {
        text-align: left;
        width: 100%;
        display: flex;
        flex-direction: row;
        justify-content: center;
        margin-top: 3%;
      }
      .cool-box {
        text-align: center;
        border: 3px solid #FCA311;
        border-radius: 5%;
        margin: 2%;
        padding: 2%;
        background-color: #14213D;
        color:#E5E5E5;
      }
      #sidebar-wrapper {
        min-height: 100vh;
        margin-left: -15rem;
        background-color: #14213D !important;
        color: #E5E5E5;
        -webkit-transition: margin .25s ease-out;
        -moz-transition: margin .25s ease-out;
        -o-transition: margin .25s ease-out;
        transition: margin .25s ease-out;
      }
      .sidebar-heading{
        color:#FCA311;
        font-family: 'Press Start 2P', cursive;
        padding: 0.1rem 1.25rem 0.875rem;
        font-size: 1.2rem;
      }
      #sidebar-wrapper .sidebar-heading {
        font-size: 1.2rem;
      }

      #sidebar-wrapper .list-group {
        width: 15rem;
      }

      #page-content-wrapper {
        min-width: 100vw;
      }

      #wrapper.toggled #sidebar-wrapper {
        margin-left: 0;
      }
      /* #menu-toggle {
        background-color: #e39774;
        color: black;
        border-color: #5C9EAD;
      } */
      .sidebar-sticky {
        position: -webkit-sticky;
        position: sticky;
        top: 14px; /* Height of navbar */
        height: calc(100vh - 48px);
   
        overflow-x: hidden;
        overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
      }
      @media (min-width: 768px) {
        #sidebar-wrapper {
          margin-left: 0;
        }

        #page-content-wrapper {
          min-width: 0;
          width: 100%;
        }

        #wrapper.toggled #sidebar-wrapper {
          margin-left: -15rem;
        }
      }
      {% block extrastyle %}
      {% endblock %}
    </style>
  </head>
  
  <body>
      <!-- <nav class="navbar sticky-top navbar-expand-md navbar-light bg-light">
        <a class="navbar-brand" href="#">GTBz Dyno</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'rosters' %}">Rosters</a>
            <a class="nav-item nav-link" href="{% url 'picks-list' %}">Draft Order</a>
            <a class="nav-item nav-link disabled" href="#" tabindex="-1" aria-disabled="true">History</a>
            <a class="nav-item nav-link disabled" href="#" tabindex="-1" aria-disabled="true">PLayers</a>
            <a class="nav-item nav-link disabled" href="#" tabindex="-1" aria-disabled="true">League Rules</a>
          </div>
        </div>
      </nav> -->
      <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div class="bg-light" id="sidebar-wrapper">
          <div class="sidebar-sticky">
          <div class="sidebar-heading">GTBz Dyno</div>
          <div class="list-group list-group-flush">
            <a class="list-group-item list-group-item-action sidebar-comp" href="{% url 'home' %}"><i class="fas fa-home"></i>Home</a>
            <a href="{% url 'rosters' %}" class="list-group-item list-group-item-action sidebar-comp"><i class="fas fa-address-card"></i>Rosters</a>
            <a href="{% url 'picks-list' %}" class="list-group-item list-group-item-action sidebar-comp"><i class="fas fa-list-ol"></i>Draft Picks</a>
            <a href="{% url 'history' %}" class="list-group-item list-group-item-action sidebar-comp"><i class="fas fa-scroll"></i>History</a>
            <a href="{% url 'rules' %}" class="list-group-item list-group-item-action sidebar-comp"><i class="fas fa-gavel"></i>League Rules</a>
            <a href="#" class="list-group-item list-group-item-action sidebar-comp disabled"><i class="fas fa-football-ball"></i>NFL Players</a>
            <div class="dropdown">
              <a class="list-group-item list-group-item-action sidebar-comp dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user-tie"></i>Teams
              </a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                {% for o in owner_list %}
                <a class="dropdown-item" href="{% url 'team' pk=o.pk %}">{{o}}</a>
                {% endfor %}
              </div>
            </div>
          </div>
          </div>
        </div>
        <!-- /#sidebar-wrapper -->
    
        <!-- Page Content -->
        <div id="page-content-wrapper">
    
          <nav class="navbar navbar-expand-lg navbar-dark nav-custom">
            
            <button class="btn btn-custom" id="menu-toggle">Toggle Menu</button>
    
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    League Links
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="https://fantasy.espn.com/football/league/rosters?leagueId=935365">ESPN Rosters</a>
                    <a class="dropdown-item" href="https://fantasy.espn.com/football/league?leagueId=935365">ESPN League Home</a>
                    <a class="dropdown-item" href="https://fantasy.espn.com/football/league/settings?leagueId=935365">ESPN League Settings</a>
                </li>
              </ul>
            </div>
          </nav>
    <!-- /#page-content-wrapper -->
          


            {% block body_block %}

            {% endblock %}

        
    
  
      </div>





    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- works but needs tweaking -->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/js/jquery.dataTables.min.js'></script> 
    <script src="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.js"></script>
    
    <!-- chart.js cdn -->
    <!-- <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js'></script> -->
    <!-- Menu Toggle Script -->
    <script>
      $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
      });
    </script>
    <script>
    {% block jquery %}{% endblock %}
    </script>

  </body>
</html>

templates/league/draftpick_list.html
{% extends "league/base.html" %}


{% block body_block %}
<div class="container-fluid" style="padding: 0px;">
<div id="primary-nav">
  <div class="container text-center">
    <div class="row newrow">
        <div class="col-md-8">
            <div class="boxy weekly">
        <h3 style="text-align: center; font-weight: 600;">2020 Draft Order</h3>

        <table id="dtBasicExample" class="table table-striped table-hover" style="margin-bottom: 0em;">
            
            <thead class="thead-custom">
            <tr>

                <th scope="col">Round</th>
                <th scope="col">Pick</th>
                <th scope="col">Owner</th>
            </tr>
            
            </thead>
            <tbody>
            {% for pick in round1 %}
            {% if forloop.last %}
            <tr class="last-row">
                <td scope="row">{{ pick.round }}</td>
                <td scope="row">{{ pick.pick }}</td>
                <td scope="row">{{ pick.owner.manager.owner_name }}</td>
            </tr>
            {% else %}
            <tr>
                <td scope="row">{{ pick.round }}</td>
                <td scope="row">{{ pick.pick }}</td>
                <td scope="row">{{ pick.owner.manager.owner_name }}</td>
            </tr>
            {% endif %}
            {% endfor %}

            </tbody>

        </table>


        <table id="dtBasicExample" class="table table-striped table-hover draft-table">
            <thead class="thead-gone">
                <tr>
    
                    <th scope="col">Round</th>
                    <th scope="col">Pick</th>
                    <th scope="col">Owner</th>
                </tr>
                
                </thead>
            <tbody>
            {% for pick in round2 %}
            {% if forloop.last %}
            <tr class="last-row">
                <td scope="row">{{ pick.round }}</td>
                <td scope="row">{{ pick.pick }}</td>
                <td scope="row">{{ pick.owner.manager.owner_name }}</td>
            </tr>
            {% else %}
            <tr>
                <td scope="row">{{ pick.round }}</td>
                <td scope="row">{{ pick.pick }}</td>
                <td scope="row">{{ pick.owner.manager.owner_name }}</td>
            </tr>
            {% endif %}
            {% endfor %}

            </tbody>

        </table>
        <table id="dtBasicExample" class="table table-striped table-hover draft-table">
            <thead class="thead-gone">
                <tr>
    
                    <th scope="col">Round</th>
                    <th scope="col">Pick</th>
                    <th scope="col">Owner</th>
                </tr>
                
                </thead>
            
            <tbody>
            {% for pick in round3 %}
            {% if forloop.last %}
            <tr class="last-row">
                <td scope="row">{{ pick.round }}</td>
                <td scope="row">{{ pick.pick }}</td>
                <td scope="row">{{ pick.owner.manager.owner_name }}</td>
            </tr>
            {% else %}
            <tr>
                <td scope="row">{{ pick.round }}</td>
                <td scope="row">{{ pick.pick }}</td>
                <td scope="row">{{ pick.owner.manager.owner_name }}</td>
            </tr>
            {% endif %}
            {% endfor %}

            </tbody>

        </table>
        <table id="dtBasicExample" class="table table-striped table-hover draft-table">
            <thead class="thead-gone">
                <tr>
                    <th scope="col">Round</th>
                    <th scope="col">Pick</th>
                    <th scope="col">Owner</th>
                </tr>  
            </thead>
            <tbody>
            {% for pick in round4 %}
            {% if forloop.last %}
            <tr class="last-row">
                <td scope="row">{{ pick.round }}</td>
                <td scope="row">{{ pick.pick }}</td>
                <td scope="row">{{ pick.owner.manager.owner_name }}</td>
            </tr>
            {% else %}
            <tr>
                <td scope="row">{{ pick.round }}</td>
                <td scope="row">{{ pick.pick }}</td>
                <td scope="row">{{ pick.owner.manager.owner_name }}</td>
            </tr>
            {% endif %}
            {% endfor %}

            </tbody>

        </table>
        <table id="dtBasicExample" class="table table-striped table-hover draft-table">
            <thead class="thead-gone">
                <tr>
    
                    <th scope="col">Round</th>
                    <th scope="col">Pick</th>
                    <th scope="col">Owner</th>
                </tr>
                
                </thead>         
            <tbody>
            {% for pick in round5 %}
            {% if forloop.last %}
            <tr class="last-row">
                <td scope="row">{{ pick.round }}</td>
                <td scope="row">{{ pick.pick }}</td>
                <td scope="row">{{ pick.owner.manager.owner_name }}</td>
            </tr>
            {% else %}
            <tr>
                <td scope="row">{{ pick.round }}</td>
                <td scope="row">{{ pick.pick }}</td>
                <td scope="row">{{ pick.owner.manager.owner_name }}</td>
            </tr>
            {% endif %}
            {% endfor %}

            </tbody>

        </table>


            </div>
        </div>

    </div>
    <div class="row newrow">
        <div class="col-md-8">
            <div class="boxy weekly">
                <h3 style="text-align: center; font-weight: 600;">2021 Draft Picks</h3>
                <table id="dtBasicExample" class="table table-striped table-hover" style="margin-bottom: 0em;">
                    
                    <thead class="thead-custom">
                    <tr>
        
                        <th scope="col">Round</th>
                        <th scope="col">Pick</th>
                        <th scope="col">Owner</th>
                    </tr>
                    
                    </thead>
                    <tbody>
                    {% for pick in p21 %}
                    <tr class="last-row">
                        <td scope="row">{{ pick.round }}</td>
                        <td scope="row">TBD</td>
                        <td scope="row">{{ pick.owner.manager.owner_name }}</td>
                    </tr>
                    {% endfor %}
        
                    </tbody>
        
                </table>
            </div>
        </div>
    </div>
    <div class="row newrow">
        <div class="col-md-8">
            <div class="boxy weekly">
                <h3 style="text-align: center; font-weight: 600;">2022 Draft Picks</h3>
                <table id="dtBasicExample" class="table table-striped table-hover" style="margin-bottom: 0em;">
                    
                    <thead class="thead-custom">
                    <tr>
        
                        <th scope="col">Round</th>
                        <th scope="col">Pick</th>
                        <th scope="col">Owner</th>
                    </tr>
                    
                    </thead>
                    <tbody>
                    {% for pick in p22 %}
                    <tr class="last-row">
                        <td scope="row">{{ pick.round }}</td>
                        <td scope="row">TBD</td>
                        <td scope="row">{{ pick.owner.manager.owner_name }}</td>
                    </tr>
                    {% endfor %}
        
                    </tbody>
        
                </table>
            </div>
        </div>
    </div>
</div>
</div>
</div>

{% endblock %}